#!/bin/sh

onSIGHUP() {
  echo "INIT: Reloading all services"
  sv reload /etc/service/*
  kill -HUP $pid
}

onSIGINT() {
  echo "INIT: Terminating all services"
  sv down /etc/service/*
  sleep 2
  kill -INT $pid
}

onSIGTERM() {
  echo "INIT: Terminating all services"
  sv down /etc/service/*
  sleep 2
  kill -TERM $pid
}

onSIGCHLD() {
  echo "SIGCHLD"
}

if [ -d /startup ]; then
  for script in /startup/*.sh; do
    sh "$script"
    ret=$?
    if [ $ret -ne 0 ]; then
      echo 'INIT ERROR: script '"$script"' exited with code '$ret
      exit $ret
    fi
  done
fi

trap onSIGHUP SIGHUP
trap onSIGINT SIGINT
trap onSIGTERM SIGTERM
trap onSIGCHLD SIGCHLD

/sbin/runsvdir -P /etc/service &
pid=$!

echo "INIT: $HOSTNAME has started"
wait $pid
echo "INIT: $HOSTNAME has halted"
